DOL.WEBAPP/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DOL.WEBAPP.Extension;
using DOL.WEBAPP.Models;
using DOL.WEBAPP.Models.Filter;
using DOL.WEBAPP.Models.Response;
using DOL.WEBAPP.Repository.AuthenticationRepository;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DOL.WEBAPP.Controllers
{
    public class SignInController : Controller
    {
        IConfiguration _configuration;

        private readonly IAuthenticationRepositories _repoCollection;

        public SignInController(IConfiguration configuration)
        {
            _configuration = configuration;

            _repoCollection = new AuthenticationRepositories(configuration);

        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            if (userInfo != null)
            {
                return RedirectToAction("Index", "Home");
            }


            return View();
        }


        [HttpPost]
        public async Task<IActionResult> VerifyAccount([FromBody] AuthenticationFilter param)
        {
            Response resp = new Response();

            try
            {

                string? roleSetting = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("Allow")["Roles"];

                resp = await Task.Run(() => _repoCollection.SignIn(param));

                if (resp.status == true)
                {

                    UserInfo userInfo = new UserInfo();

                    SysUserResponse sysUser = new SysUserResponse();

                    sysUser = JsonConvert.DeserializeObject<SysUserResponse>(resp.data.ToString());

                    AppHelper.TransferData_ClassA_to_ClassB<SysUserResponse, UserInfo>(sysUser, ref userInfo, new List<string>());

                    string[] rolesArray = roleSetting.Split(',');

                    // Convert the array to a List<string> if needed
                    List<string> rolesList = rolesArray.ToList();

                    if (rolesList.Contains(userInfo.UserGroup.ToLower()))
                    {
                        SessionHelper.SetObjectAsJson(this.HttpContext.Session, "UserInfo", userInfo);
                    }

                    else
                    {
                        resp.statusCode = 403;
                    }

                }
            }
            catch (Exception ex)
            {
                resp.status = false;
                resp.exception = ex.Message;
            }

            return new JsonResult(resp);
        }
    }
}

DOL.WEBAPP/Views/SignIn/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Onsite - DOL  | uihservices.com</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="custom/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="custom/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="custom/favicon/favicon-16x16.png">
    <link rel="manifest" href="custom/favicon/site.webmanifest">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.7/dist/sweetalert2.min.css">
</head>

<body class="custom-bg-gradient noto-sans">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row" style="height:350px">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        @*<img class="img-profile rounded-circle" width="200" src="custom/images/logo-no-text.png">*@

                                        <h1 class="h4 text-gray-900 mb-4" style="font-weight:600">ทีมติดตั้ง</h1>
                                    </div>
                                    <form class="user needs-validation" id="formSignIn" novalidate>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" id="InputUsername" placeholder="Username" required style="font-size:1rem">
                                            <div class="invalid-feedback">
                                                Please enter InputUsername
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" autocomplete="off" class="form-control form-control-user" id="InputPassword" placeholder="Password" required style="font-size:1rem">
                                            <div class="invalid-feedback">
                                                Please enter InputPassword
                                            </div>
                                        </div>

                                        <div class="custom-row-button-login border-top">
                                            <div class="pt-3 pb-3" style="padding-right: 50px;">
                                                <button type="submit" class="btn btn-primary btn-user custom-login-button">
                                                    Login
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="vendor/jquery/jquery.min.js"></script>

    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="js/sb-admin-2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.7/dist/sweetalert2.all.min.js"></script>


    <script>

        document.addEventListener('DOMContentLoaded', function () {
            setTimeout(function () {

                $("#InputUsername").focus();

            }, 500);
        });

        $(function () {

            $("#formSignIn").on("submit", function () {

                var form = $(this)[0];

                if (form.checkValidity() === false) {
                    event.preventDefault();

                    event.stopPropagation();

                    form.classList.add('was-validated');
                }
                else {

                    var param = getModel();

                    event.preventDefault();
                    event.stopPropagation();

                    $.ajax({
                        type: 'Post',
                        url: '@Url.Action("VerifyAccount", "SignIn")',
                        data: JSON.stringify(param),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (data) {

                            if (data.status == true) {

                                if (data.statusCode == 403) {
                                    window.location.href = "@Url.Action("Error403", "Error")";
                                }
                                else {
                                    window.location.href = "@Url.Action("Index","Home")";
                                }
                            }
                            else {

                                event.preventDefault();
                                event.stopPropagation();

                                OnSaveError(data.message);

                            }
                        },
                        fail: function () {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                    });

                }
            });

        });

        function getModel() {

            var data = new Object();

            data.userName = $('#InputUsername').val();
            data.password = $('#InputPassword').val();

            return data;

        }

    </script>

    <script type="text/javascript">function OnSaveSuccess(message) {

            Swal.fire({
                icon: 'success',
                html: message,
                type: 'success',
                buttonsStyling: true,

                //sweet alert for "Confirm" Buttom
                showConfirmButton: true,
                confirmButtonColor: '#3085d6',
                confirmButtonClass: 'btn-flat shadow btn btn-success',
                confirmButtonText: 'ตกลง',

            })
        }

        function OnSaveError(message) {
            Swal.fire({
                icon: 'error',
                html: message,
                type: 'error',
                buttonsStyling: true,

                //sweet alert for "Cancel" Buttom
                showCancelButton: true,
                cancelButtonColor: '#d33',
                cancelButtonClass: 'btn-flat shadow btn btn-danger ml-1',
                cancelButtonText: 'ลองใหม่อีกครั้ง !',

                //sweet alert for "Confirm" Buttom
                showConfirmButton: false,
                confirmButtonColor: '#3085d6',
                confirmButtonClass: 'btn-flat shadow btn btn-success',
                confirmButtonText: 'ตกลง',

            })
        }

        function OnSaveWarning(message) {
            Swal.fire({
                icon: 'warning',
                html: message,
                type: 'warning',
                buttonsStyling: true,

                //sweet alert for "Cancel" Buttom
                showCancelButton: true,
                cancelButtonColor: '#d33',
                cancelButtonClass: 'btn-flat shadow btn btn-danger ml-1',
                cancelButtonText: 'ลองใหม่อีกครั้ง !',

                //sweet alert for "Confirm" Buttom
                showConfirmButton: false,
                confirmButtonColor: '#3085d6',
                confirmButtonClass: 'btn-flat shadow btn btn-success',
                confirmButtonText: 'ตกลง',

            })
        }</script>

    <style>
        .custom-bg-gradient {
            background: transparent linear-gradient(156deg, #667DE9 0%, #764CA3 100%) 0% 0% no-repeat padding-box;
        }

        .form-control-user {
            border-radius: 0.5rem !important;
        }

        .noto-sans {
            font-family: "Noto Sans Thai", sans-serif;
            font-optical-sizing: auto;
            font-weight: 100 900;
            font-style: normal;
            font-variation-settings: "wdth" 100;
        }

        .custom-login-button {
            width: 200px;
            float: inline-end;
            border-radius: 5px !important;
            background-color: #545CD8;
        }

        .custom-row-button-login {
            position: absolute;
            height: 150px;
            width: 100%;
            background: #F8F9FA 0% 0% no-repeat padding-box;
            left: 10px;
        }
    </style>

</body>

</html>