DOL.WEBAPP/Controllers/JobDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DOL.WEBAPP.Extension;
using DOL.WEBAPP.Models.Filter;
using DOL.WEBAPP.Models.Response;
using DOL.WEBAPP.Repository.AuthenticationRepository;
using DOL.WEBAPP.Repository.JobOnsiteRepository;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DOL.WEBAPP.Controllers
{
    public class JobDashboardController : Controller
    {
        IConfiguration _configuration;

        private readonly IJobOnsiteRepository _repoCollection;

        public JobDashboardController(IConfiguration configuration)
        {
            _configuration = configuration;

            _repoCollection = new JobOnsiteRepository(configuration);

        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            if (userInfo == null)
            {
                return RedirectToAction("Index", "SignIn");
            }


            return View(userInfo);
        }


        public async Task<IActionResult> Get(SiteInformationFilter param)
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            Response resp = new Response();

            if (userInfo == null)
            {
                return RedirectToAction("Index", "SignIn");
            }

            else
            {
                param.SysUserId = userInfo.Id;

                resp = await Task.Run(() => _repoCollection.CardJobs(param));
            }


            return new JsonResult(resp);
        }
    }
}

DOL.WEBAPP/Controllers/JobDetailController.cs
using System.Reflection.Metadata;
using DOL.WEBAPP.Extension;
using DOL.WEBAPP.Models.Request;
using DOL.WEBAPP.Models.Response;
using DOL.WEBAPP.Repository.JobOnsiteRepository;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Document = iTextSharp.text.Document;
using System.IO;
using System.Text;
using static Org.BouncyCastle.Bcpg.Attr.ImageAttrib;

namespace DOL.WEBAPP.Controllers
{
    public class JobDetailController : Controller
    {
        IConfiguration _configuration;

        private IWebHostEnvironment _hostingEnvironment;

        private readonly IJobOnsiteRepository _repoCollection;

        public JobDetailController(IConfiguration configuration, IWebHostEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
            _repoCollection = new JobOnsiteRepository(configuration);

        }
        // GET: /<controller>/

        public async Task<IActionResult> Index(int id)
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            Response resp = new Response();

            SiteInformationResponse result = new SiteInformationResponse();

            if (userInfo == null)
            {
                return RedirectToAction("Index", "SignIn");
            }
            else
            {
                resp = await Task.Run(() => _repoCollection.Detail(id));

                if (resp.status == true)
                {
                    var aaa = JsonConvert.SerializeObject(resp.data);

                    result = JsonConvert.DeserializeObject<SiteInformationResponse>(aaa);

                    if (result.SysUserId != userInfo.Id)
                    {
                        return RedirectToAction("Error403", "Error");
                    }
                }
            }

            return View(result);
        }


        // GET: /<controller>/
        [HttpPost]
        public async Task<IActionResult> Update([FromBody] SiteInformationRequest param)
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            Response resp = new Response();

            SiteInformationResponse result = new SiteInformationResponse();

            if (userInfo == null)
            {
                return RedirectToAction("Index", "SignIn");
            }
            else
            {
                resp = await Task.Run(() => _repoCollection.Update(param));

                if (resp.status == true)
                {
                    var aaa = JsonConvert.SerializeObject(resp.data);

                    result = JsonConvert.DeserializeObject<SiteInformationResponse>(aaa);
                }


            }

            return new JsonResult(resp);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateImage(SiteInformationRequest param)
        {
            UserInfo userInfo = SessionHelper.GetObjectFromJson<UserInfo>(this.HttpContext.Session, "UserInfo");

            string? folderUploadFile = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("Settings")["ApiRootUploadSiteinformation"];


            Response resp = new Response();

            //UpdateImageRequest objImage = new UpdateImageRequest();

            UpdateImageNameRequest objImage = new UpdateImageNameRequest();

            try
            {
                if (userInfo == null)
                {
                    return RedirectToAction("Index", "SignIn");
                }
                else
                {
                    if (Request.Form.Files.Count >= 1)
                    {
                        foreach (var fileUpload in Request.Form.Files)
                        {
                            switch (fileUpload.Name)
                            {
                                case "UploadImage1":
                                    param.TypeOnsiteValue = "image1";
                                    break;
                                case "UploadImage2":
                                    param.TypeOnsiteValue = "image2";
                                    break;
                                case "UploadImage3":
                                    param.TypeOnsiteValue = "image3";
                                    break;
                                case "UploadImage4":
                                    param.TypeOnsiteValue = "image4";
                                    break;
                                case "UploadImage5":
                                    param.TypeOnsiteValue = "image5";
                                    break;
                                case "UploadImage6":
                                    param.TypeOnsiteValue = "image6";
                                    break;
                                case "UploadImage7":
                                    param.TypeOnsiteValue = "image7";
                                    break;
                                case "UploadImage8":
                                    param.TypeOnsiteValue = "image8";
                                    break;
                                case "UploadImage9":
                                    param.TypeOnsiteValue = "image9";
                                    break;
                                case "UploadImage10":
                                    param.TypeOnsiteValue = "image10";
                                    break;
                                case "UploadImage11":
                                    param.TypeOnsiteValue = "image11";
                                    break;
                                case "UploadImage12":
                                    param.TypeOnsiteValue = "image12";
                                    break;
                                case "UploadImage13":
                                    param.TypeOnsiteValue = "image13";
                                    break;
                                case "UploadImage14":
                                    param.TypeOnsiteValue = "image14";
                                    break;
                                case "UploadImage15":
                                    param.TypeOnsiteValue = "image15";
                                    break;
                                case "UploadImage16":
                                    param.TypeOnsiteValue = "image16";
                                    break;
                                case "UploadImage17":
                                    param.TypeOnsiteValue = "image17";
                                    break;
                                case "UploadImage18":
                                    param.TypeOnsiteValue = "image18";
                                    break;
                                case "UploadImage19":
                                    param.TypeOnsiteValue = "image19";
                                    break;
                                case "UploadImage20":
                                    param.TypeOnsiteValue = "image20";
                                    break;
                                case "UploadImage21":
                                    param.TypeOnsiteValue = "image21";
                                    break;
                                case "UploadImage22":
                                    param.TypeOnsiteValue = "image22";
                                    break;
                                case "UploadImage23":
                                    param.TypeOnsiteValue = "image23";
                                    break;
                                case "UploadImage24":
                                    param.TypeOnsiteValue = "image24";
                                    break;
                                //case "UploadImage25":
                                //    param.TypeOnsiteValue = "image25";
                                //    break;
                                case "UploadImage26":
                                    param.TypeOnsiteValue = "image26";
                                    break;
                                case "UploadImage27":
                                    param.TypeOnsiteValue = "image27";
                                    break;
                                case "UploadImage28":
                                    param.TypeOnsiteValue = "image28";
                                    break;
                                case "UploadImage29":
                                    param.TypeOnsiteValue = "image29";
                                    break;
                                case "UploadImage30":
                                    param.TypeOnsiteValue = "image30";
                                    break;
                                case "UploadImage31":
                                    param.TypeOnsiteValue = "image31";
                                    break;
                                case "UploadImage32":
                                    param.TypeOnsiteValue = "image32";
                                    break;
                                case "UploadImage33":
                                    param.TypeOnsiteValue = "image33";
                                    break;
                                case "UploadImage34":
                                    param.TypeOnsiteValue = "image34";
                                    break;
                                case "UploadImage35":
                                    param.TypeOnsiteValue = "image35";
                                    break;
                                case "UploadImage36":
                                    param.TypeOnsiteValue = "image36";

DOL.WEBAPP/Views/JobDashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model DOL.WEBAPP.Models.Response.UserInfo


@section Style {
    @await Html.PartialAsync("_Style")
}

@await Html.PartialAsync("_Content")

@section Scripts {
    @await Html.PartialAsync("_Script", Model)
}

DOL.WEBAPP/Views/JobDashboard/_Content.cshtml
                <!-- Begin Page Content -->
<div class="container-fluid custom-height-screen">

    <!-- Page Heading -->

    <div class="align-items-center justify-content-between">
        @*<span class="h5 mb-0 text-gray-800" onclick="backToPrevious()" style="cursor:pointer"> หน้าแรก / </span>*@

        <div class="row">
            <div class="col-7">
                <span class="h5 mb-0 text-gray-800" style="font-size: 25px; font-weight:bold;"> ตารางงานทั้งหมด </span>
            </div>
            <div class="col-5">
                <div class="form-group">
                    <select class="form-control" id="selectStatus" onchange="onSearch()">
                        <option value="">All status</option>
                        <option value="2">Pending</option>
                        <option value="3">On process</option>
                        <option value="4">Complete</option>
                    </select>
                </div>
            </div>
        </div>



    </div>

    <hr style="border-top: 3px solid #575757; " />

    <div class="row pb-2">
        <div class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" style="width:100%">
            <div class="input-group">
                <input type="text" id="txtSearch" class="form-control form-control-lg bg-white border-0 small" placeholder="" aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn" style="background-color: white;" type="button" onclick="onSearch()">
                        <i class="fas fa-search fa-sm" style="font-size: 25px; color: #575757;"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row" id="sectionRender">

        <!-- Earnings (Monthly) Card Example -->
        @*<div class="col-12 col-md-6 mb-4">
                <div class="custom-card-job">
                    <div class="pl-3 pt-4">
                        <label class="h5">ชื่อสถานที่ </label>
                    </div>

                    <div class="icon-tel">
                        <i class="fas fa-phone-alt"></i>
                    </div>

                    <div class="icon-plane">
                        <i class="fas fa-paper-plane"></i>
                    </div>

                    <div class="pl-3">
                        <small>(ภาคผนวก)</small>
                    </div>

                    <div class="pl-3 pt-5">
                        <label> Address </label>
                    </div>

                    <div class="custom-row-status">
                        Complete
                    </div>
                </div>
            </div>*@

    </div>


</div>
<!-- /.container-fluid -->

DOL.WEBAPP/Views/JobDashboard/_Script.cshtml
@model DOL.WEBAPP.Models.Response.UserInfo

<script type="text/javascript">

    document.addEventListener('DOMContentLoaded', function () {

        onSearch();

        setTimeout(function () {

            $("#txtSearch").focus();

        }, 1000);
    });

    $(document).keypress(function (e) {
        if (e.which == 13) {
            onSearch();
        }
    });

    function backToPrevious() {
        window.location.href = "@Url.Action("Index", "Home")";
    }


    function onSearch() {

        var filter = new Object();

        filter.TextSearch = $("#txtSearch").val();
        filter.SysStatusId = $("#selectStatus").val();
        filter.IsAll = true;

        $.ajax({
            type: "Get",
            contentType: "charset=utf-8",
            data: filter,
            url: '@Url.Action("Get", "JobDashboard")',
            success: function (resp) {

                if (resp.status) {

                    $('#sectionRender').html('')

                    resp.data.forEach((item) => {

                        var htmlRender = ``;

                        var cardBg = ``;
                        var cardStatusBg = ``;

                        var linkTel = ``;
                        var linkMap = ``;


                        if (item.statusId == 2) {
                            cardBg = `custom-card-job-danger`;
                            cardStatusBg = `custom-row-status-danger`;
                        }

                        if (item.statusId == 3) {
                            cardBg = `custom-card-job-warning`;
                            cardStatusBg = `custom-row-status-warning`;
                        }

                        if (item.statusId == 9) {
                            cardBg = `custom-card-job-info`;
                            cardStatusBg = `custom-row-status-info`;
                        }

                        if (item.statusId == 4) {
                            cardBg = `custom-card-job-success`;
                            cardStatusBg = `custom-row-status-success`;
                        }

                        if (item.tel != null && item.tel != "") {

                            linkTel = `<div class="icon-tel">
                                            <a href="tel:${item.tel}" target="_blank" style="color: #858796;">
                                                <i class="fas fa-phone-alt" style="font-size:20px"></i>
                                            </a>
                                        </div>`;
                        }
                        else {
                            linkTel = ``;
                        }

                        if (item.googleMap != null && item.googleMap != "") {
                            linkMap = `href="${item.googleMap}" target="_blank"`;
                        }

                        htmlRender = `<div class="col-12 col-md-12 col-lg-6 col-xl-6 mb-4" style="cursor:pointer">
                                    <div class="${cardBg}">

                                       ${linkTel}

                                        <div class="icon-plane">
                                            <a ${linkMap} style="color: #858796;">
                                                <i class="fas fa-paper-plane" style="font-size:20px"></i>
                                            </a>
                                        </div>

                                        <div class="pl-3 pt-4" onclick="onDetail(${item.id})">
                                            <label style="font-size: 20px; color: black; font-weight: 500;">${item.locationName} </label>
                                        </div>

                                        <div class="pl-3" onclick="onDetail(${item.id})">
                                            <h6 style="color:#000000">( ${item.networkName} )</small>
                                        </div>

                                        <div class="pl-3 pt-5" onclick="onDetail(${item.id})">
                                            <label style="color:#000000"> ${item.address} </label>
                                        </div>

                                        <div class="${cardStatusBg}" onclick="onDetail(${item.id})">
                                            ${item.statusName}
                                        </div>
                                    </div>
                                </div>`;


                        $('#sectionRender').append(htmlRender)


                    });

                }
                else {
                    $('#sectionRender').html('')
                }
            }
        });
    }

    function onDetail(id) {

        window.location.href = "@Url.Action("Index", "JobDetail")?id=" + id;

    }

</script>

DOL.WEBAPP/Views/JobDashboard/_Style.cshtml
<style>

    .custom-height-screen {
        height: 50em;
    }


    .custom-card-job-success {
        height: auto;
        background: #E5FFF2 0% 0% no-repeat padding-box;
        box-shadow: 0px 6px 6px #00000029;
        opacity: 1;
    }

    .custom-row-status-success {
        color: white;
        height: 50px;
        background-color: #3AC47D;
        align-content: center;
        text-align: center;
        font-weight: 800;
        font-size: x-large;
    }




    .custom-card-job-warning {
        height: auto;
        background: #FFF7E5 0% 0% no-repeat padding-box;
        box-shadow: 0px 6px 6px #00000029;
        opacity: 1;
    }

    .custom-row-status-warning {
        color: white;
        height: 50px;
        background-color: #F7BA25;
        align-content: center;
        text-align: center;
        font-weight: 800;
        font-size: x-large;
    }





    .custom-card-job-danger {
        height: auto;
        background: #FFD9E3 0% 0% no-repeat padding-box;
        box-shadow: 0px 6px 6px #00000029;
        opacity: 1;
    }

    .custom-row-status-danger {
        color: white;
        height: 50px;
        background-color: #D92450;
        align-content: center;
        text-align: center;
        font-weight: 800;
        font-size: x-large;
    }


    .custom-card-job-info {
        height: auto;
        background: #DBB2F5 0% 0% no-repeat padding-box;
        box-shadow: 0px 6px 6px #00000029;
        opacity: 1;
    }

    .custom-row-status-info {
        color: white;
        height: 50px;
        background-color: #545CD8;
        align-content: center;
        text-align: center;
        font-weight: 800;
        font-size: x-large;
    }



    .icon-tel {
        position: absolute;
        top: 8px;
        right: 60px;
    }

    .icon-plane {
        position: absolute;
        top: 8px;
        right: 25px;
    }
</style>